### PR TITLE
Fix: squid:S2293, The operator ("<>") should be used.

### PR DESCRIPTION
**Pull request by elkfrawy-df**
This pull request is focused on resolving occurrences of Sonar rule 
 squid:S2293 - “The diamond operator ("<>") should be used ”. 
 You can find more information about the issue here: 
 https://dev.eclipse.org/sonar/rules/show/squid:S2293

 Please let me know if you have any questions.
Ayman Elkfrawy.

### CODE REVIEW

**Comment by robertpanzer** [comment]
If I see it correctly the code is compiled with source and target version 1.6. 
So this would be a problem I guess. 
Same with the try-with-resources PR.

**Comment by elkfrawy-df** [comment]
Yes, I saw that, I asked @danielsoro before doing this and he told me that minimum JDK is 1.7, so if it is 1.6 then these should be closed.

**Comment by elkfrawy-df** [comment]
https://github.com/tomitribe/tomitribe-oss-parent/blob/master/pom.xml#L327-L335

**Comment by robertpanzer** [comment]
But it currently uses this one: https://github.com/tomitribe/tomitribe-oss-parent/blob/939ff61d45f5a2497aa4e6df32048470bdc28461/pom.xml#L327
Did you build this PR? can't imagine at the moment that a mvn compile would work. 
While it's imo fine to upgrade the Java version it should be a dedicated decision. If there are still users sitting on Java 6 they would be turned off immediately.
(I am not against this, just has to be clear)

**Comment by danielsoro** [comment]
It seems that crest use version 2 of the tomitribe-oss-parent that already is java 6.
@elkfrawy-df , @robertpanzer is right.

**Comment by danielsoro** [comment]
@robertpanzer I agree to update the parent on crest. :)

**Comment by elkfrawy-df** [comment]
That is your decision then.

**Comment by robertpanzer** [comment]
I am fine as well, ;-)  
But I don't know all constraints. 
Maybe @rmannibucau has an opinion on upgrading to the current oss-parent and Java 7.

**Comment by rmannibucau** [comment]
Had some concerns about java 6 cause wanted to use it for some OSS products but has been solved since so j7 is fine today (and before you ask not j8 ;)).

**Comment by danielsoro** [comment]
@elkfrawy-df Now crest is JDK7. :)
Please review your PR and update it.

**Comment by elkfrawy-df** [comment]
@danielsoro Thanks, I have resolved the conflict.
Please let me know if you want me to do something else.

**Pull request merged**
