### PR TITLE
Fix: squid:S1596, Collections.emptyList(), emptyMap() and emptySet() …

### PR DESCRIPTION
**Pull request by elkfrawy-df**
This pull request is focused on resolving occurrences of Sonar rule 
 squid:S1596 - “Collections.emptyList(), emptyMap() and emptySet() should be used instead of Collections.EMPTY_LIST, EMPTY_MAP and EMPTY_SET”. 
 You can find more information about the issue here: 
 https://dev.eclipse.org/sonar/rules/show/squid:S1596

 Please let me know if you have any questions.
Ayman Elkfrawy.

### CODE REVIEW

**Comment by rmannibucau** [comment]
Comment is not accurate with diff. Is it a spam as on asf lists?

**Comment by danielsoro** [comment]
@rmannibucau No.

**Comment by elkfrawy-df** [comment]
@rmannibucau this is not spam, I made the changes and pull request myself. We wrote the comment is a standard way, which include the rule key for Sonar rule, and the description of that rule. If you want me to change this to a custom message that is fine

**Comment by rmannibucau** [comment]
Yes, having a description of what is done in the PR is generally more useful than an automated message, in particular when it doesnt match.

**Comment by elkfrawy-df** [comment]
@rmannibucau I changed the message.

**Pull request merged**
